### ISSUE TITLE
Use the latest version of peaceiris/actions-gh-pages

### ISSUE THREAD

**Issue by peaceiris** [buchen/portfolio-help#3]
Check your GitHub Pages status, you find that GitHub Pages build event did not start.

- Please do not use `GITHUB_TOKEN`, use `ACTIONS_DEPLOY_KEY` or `PERSONAL_TOKEN` 
  - cf. https://github.com/peaceiris/actions-gh-pages/issues/9
- Please use the latest version of peaceiris/actions-gh-pages
  - [Releases · peaceiris/actions-gh-pages](https://github.com/peaceiris/actions-gh-pages/releases)

**Comment by buchen** [comment]
Thanks! Updated my workflow.
