### ISSUE TITLE
Beim Start von PP öffnen sich zwei Fenster

### ISSUE THREAD

**Issue by DirkBalthasar** [buchen/portfolio-help#7]
Hallo, 

in der aktuellen Version hat sich ein kleiner Fehler eingeschlichen - es öffnet sich bei Programmstart immer ein leeres Fenster mit Menü.
Von dort kann ich dann das zuletzt verwendete File auswählen, welches in einem zweiten Fenster öffnet.
Beide Fenster muss man nach verrichteter Arbeit auch wieder schließen.

Leider öffnet PP beim darauffolgenden Start das zuletzt verwendete File nicht mehr automatisch. (War bei alten Versionen so.)

Version: 0.48.1 (Sep. 2020)
Platform: win32, x86_64
Java: 11.0.4+11-LTS, Azul Systems, Inc.

Liebe Grüße und vielen Dank für das großartige Werkzeug PP!
Dirk

**Comment by buchen** [comment]
Sorry, in diesem Projekt geht es - wenn überhaupt - nur um Fehler in der Dokumentation. (Ein Grund warum ich dieses Projekt nicht wirklich beobachte). Also ggf. hier öffnen: https://github.com/buchen/portfolio/issues Da das Ticket schon recht alt ist, schließe ich das hier.
